### ISSUE TITLE
Cannot see menu buttons on top of selected widgets.

### ISSUE THREAD

**Issue by jgwhite0111** [B00merang-Project/Solaris-8#1]
OS: Ubuntu 20.04

The below screenshot shows how a user can click a menu-button to reveal a drop-down menu in the preferences of gnome-terminal.

![j43rIe.png](https://i.lensdump.com/i/j43rIe.png)

The problem: the drop-down button isn't visible unless the user hovers over it. Some users might not guess the button is there. See below how there is no drop-down button next to 'Default' label?

![j43iyA.png](https://i.lensdump.com/i/j43iyA.png)

I've added the following in `gtk.css`: 

```
list row:selected button:not(:hover):not(:checked) {
  color: #bebebe;
}
```

And in `gtk-dark.css`:

```
list row:selected button:not(:hover):not(:checked) {
  color: #7287c0;
}
```

Now the drop-down menu button is easily discoverable:

![j43AJD.png](https://i.lensdump.com/i/j43AJD.png)

As I'm not experienced with CSS or GNOME, please let me know if it needs re-writing. The style is limited to ListBox to avoid conflicts with future theme updates. I'll let you know if I find any other instances where selection colour hides other element visibility.

Great theme by the way.

**Comment by Elbullazul** [comment]
thanks for reporting, we'll try to have it fix on the next code push

**Comment by jgwhite0111** [comment]
> thanks for reporting, we'll try to have it fix on the next code push

OK. Thankyou.

**Comment by Elbullazul** [comment]
fixed
